### ISSUE TITLE
spark shell connection problem

### ISSUE THREAD

**Issue by AlexanderRiggers** [amplab/training#147]
Hello 

Everytime I want to start the spark shell I get this error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/repl/Main
Caused by: java.lang.ClassNotFoundException: org.apache.spark.repl.Main
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

What am I missing?

Kind regards

**Comment by xhudik** [comment]
easy question - you are missing: org.apache.spark.repl.Main
The better question would be - why the class is missing and how to fix it. But for such questions you are not providing enough info and it would be better to ask them on stackoverflow.com which is well suited for answering programming questions (github is more about sw improvements and bugs)
