### ISSUE TITLE
Major errors in first two commands in Shark section "8. Data Exploration Using Shark"

### ISSUE THREAD

**Issue by andyk** [amplab/training#17]
I see the following when I run the first two commands under the Shark section:

``` text
CREATE EXTERNAL TABLE wikistats (dt string, project_code string, page_name string, page_views int, bytes int) row format delimited fields terminated by ' ' location '/wiki/pagecounts';
...
13/02/05 21:22:16 INFO ql.Driver: <PERFLOG method=compile>
13/02/05 21:22:16 INFO parse.ParseDriver: Parsing command: CR
FAILED: Parse Error: line 1:0 cannot recognize input near 'CR' '<EOF>' '<EOF>'

13/02/05 21:22:16 ERROR shark.SharkDriver: FAILED: Parse Error: line 1:0 cannot recognize input near 'CR' '<EOF>' '<EOF>'

org.apache.hadoop.hive.ql.parse.ParseException: line 1:0 cannot recognize input near 'CR' '<EOF>' '<EOF>'

    at org.apache.hadoop.hive.ql.parse.ParseDriver.parse(ParseDriver.java:440)
    at shark.SharkDriver.compile(SharkDriver.scala:183)
    at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:336)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:909)
    at shark.SharkCliDriver.processCmd(SharkCliDriver.scala:281)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:341)
    at shark.SharkCliDriver$.main(SharkCliDriver.scala:196)
    at shark.SharkCliDriver.main(SharkCliDriver.scala)

13/02/05 21:22:16 INFO ql.Driver: </PERFLOG method=compile start=1360099336167 end=1360099336173 duration=6>
13/02/05 21:22:16 INFO ql.Driver: <PERFLOG method=releaseLocks>
13/02/05 21:22:16 INFO ql.Driver: </PERFLOG method=releaseLocks start=1360099336173 end=1360099336173 duration=0>
```

Then for the 2nd command:

``` text
create table wikistats_cached as select * from wikistats where project_code="en";
...
13/02/05 21:25:30 INFO storage.MemoryStore: ensureFreeSpace(48415) called with curMem=0, maxMem=2037425111
13/02/05 21:25:30 INFO storage.MemoryStore: Block broadcast_0 stored as values to memory (estimated size 47.3 KB, free 1943.0 MB)
java.lang.NoSuchMethodError: de.javakaffee.kryoserializers.KryoReflectionFactorySupport.register(Ljava/lang/Class;)Lcom/esotericsoftware/kryo/Kryo$RegisteredClass;
    at spark.KryoSerializer$$anonfun$createKryo$1.apply(KryoSerializer.scala:213)
    at spark.KryoSerializer$$anonfun$createKryo$1.apply(KryoSerializer.scala:212)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at spark.KryoSerializer.createKryo(KryoSerializer.scala:212)
    at spark.KryoSerializer.kryo(KryoSerializer.scala:176)
    at spark.KryoSerializerInstance.<init>(KryoSerializer.scala:102)
    at spark.KryoSerializer.newInstance(KryoSerializer.scala:278)
    at spark.broadcast.HttpBroadcast$.write(HttpBroadcast.scala:107)
    at spark.broadcast.HttpBroadcast.<init>(HttpBroadcast.scala:27)
    at spark.broadcast.HttpBroadcastFactory.newBroadcast(HttpBroadcast.scala:53)
    at spark.broadcast.HttpBroadcastFactory.newBroadcast(HttpBroadcast.scala:49)
    at spark.broadcast.BroadcastManager.newBroadcast(Broadcast.scala:50)
    at spark.SparkContext.broadcast(SparkContext.scala:408)
    at spark.rdd.HadoopRDD.<init>(HadoopRDD.scala:52)
    at spark.SparkContext.hadoopRDD(SparkContext.scala:224)
    at shark.execution.TableScanOperator.shark$execution$TableScanOperator$$createHadoopRdd(TableScanOperator.scala:273)
    at shark.execution.TableScanOperator.preprocessRdd(TableScanOperator.scala:174)
    at shark.execution.UnaryOperator.execute(Operator.scala:191)
    at shark.execution.TableScanOperator.execute(TableScanOperator.scala:108)
    at shark.execution.Operator$$anonfun$executeParents$1.apply(Operator.scala:114)
    at shark.execution.Operator$$anonfun$executeParents$1.apply(Operator.scala:114)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
    at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:47)
    at shark.execution.Operator.executeParents(Operator.scala:114)
    at shark.execution.UnaryOperator.execute(Operator.scala:190)
    at shark.execution.Operator$$anonfun$executeParents$1.apply(Operator.scala:114)
    at shark.execution.Operator$$anonfun$executeParents$1.apply(Operator.scala:114)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
    at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:47)
    at shark.execution.Operator.executeParents(Operator.scala:114)
    at shark.execution.UnaryOperator.execute(Operator.scala:190)
    at shark.execution.Operator$$anonfun$executeParents$1.apply(Operator.scala:114)
    at shark.execution.Operator$$anonfun$executeParents$1.apply(Operator.scala:114)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:60)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
    at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:47)
    at shark.execution.Operator.executeParents(Operator.scala:114)
    at shark.execution.CacheSinkOperator.execute(TerminalOperator.scala:198)
    at shark.execution.SparkTask.execute(SparkTask.scala:93)
    at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:134)
    at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
    at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1326)
    at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1118)
    at org.apache.hadoop.hive.ql.Driver.run(Driver.java:951)
    at shark.SharkCliDriver.processCmd(SharkCliDriver.scala:281)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:406)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:341)
    at shark.SharkCliDriver$.main(SharkCliDriver.scala:196)
    at shark.SharkCliDriver.main(SharkCliDriver.scala)
FAILED: Execution Error, return code -101 from shark.execution.SparkTask
13/02/05 21:25:30 ERROR ql.Driver: FAILED: Execution Error, return code -101 from shark.execution.SparkTask
13/02/05 21:25:30 INFO ql.Driver: </PERFLOG method=Driver.execute start=1360099530181 end=1360099530393 duration=212>
13/02/05 21:25:30 INFO ql.Driver: <PERFLOG method=releaseLocks>
13/02/05 21:25:30 INFO ql.Driver: </PERFLOG method=releaseLocks start=1360099530393 end=1360099530393 duration=0>
```

**Comment by JoshRosen** [comment]
cc @rxin

**Comment by pwendell** [comment]
Are you entering these commands with linebreaks?

**Comment by andyk** [comment]
I guess I copied the line break at the end of the first one. it seems to run fine now (when i don't include the line break), the 2nd one is still crashing as above.

**Comment by rxin** [comment]
Problem solved. To leave a trail: problem was two different versions of
kryo library existing on the same path.

**Comment by shivaram** [comment]
Fixed in the new AMI ....
