### ISSUE TITLE
Cluster launch failed via spark-ec2 with Broken Pipe error

### ISSUE THREAD

**Issue by andyk** [amplab/training#37]
I tried launching a new cluster via the following:

```
./spark-ec2 -i ~/.ec2/andyk-ec2.pem -k andyk-ec2 --copy launch ampcamp
```

But this failed after a few minutes with:

``` text
ec2-50-16-22-140.compute-1.amazonaws.com: 
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
13/02/24 04:01:32 INFO tools.DistCp: srcPaths=[s3n://ampcamp-data/wikistats_20090505-04]
13/02/24 04:01:32 INFO tools.DistCp: destPath=hdfs://ip-10-30-145-36.ec2.internal:9000/wiki/pagecounts
13/02/24 04:01:44 INFO tools.DistCp: hdfs://ip-10-30-145-36.ec2.internal:9000/wiki/pagecounts does not exist.
13/02/24 04:01:44 INFO tools.DistCp: sourcePathsCount=76
13/02/24 04:01:44 INFO tools.DistCp: filesToCopyCount=75
13/02/24 04:01:44 INFO tools.DistCp: bytesToCopyCount=18.5g
13/02/24 04:01:46 INFO mapred.JobClient: Running job: job_201302240401_0001
13/02/24 04:01:47 INFO mapred.JobClient:  map 0% reduce 0%
Write failed: Broken pipe
Traceback (most recent call last):
  File "./spark_ec2.py", line 867, in <module>
    main()
  File "./spark_ec2.py", line 722, in main
    copy_ampcamp_data(master_nodes, opts)
  File "./spark_ec2.py", line 493, in copy_ampcamp_data
    "hdfs://`hostname`:9000/wiki/pagecounts")
  File "./spark_ec2.py", line 663, in ssh
    (opts.identity_file, opts.user, host, command), shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -t -o StrictHostKeyChecking=no -i /Users/andyk/.ec2/andyk-ec2.pem root@ec2-23-20-148-178.compute-1.amazonaws.com '/root/ephemeral-hdfs/bin/hadoop distcp s3n://ampcamp-data/wikistats_20090505-04 hdfs://`hostname`:9000/wiki/pagecounts'' returned non-zero exit status 255
```

So I tried:

```
./spark-ec2 -i ~/.ec2/andyk-ec2.pem -k andyk-ec2 --copy launch --resume ampcamp
```

But eventually got:

``` text
Waiting for cluster to start...
Spark master reports 6 CPUs, expected 6
stopping jobtracker
ec2-23-23-65-191.compute-1.amazonaws.com: stopping tasktracker
ec2-50-16-22-140.compute-1.amazonaws.com: stopping tasktracker
ec2-174-129-81-192.compute-1.amazonaws.com: stopping tasktracker
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
starting jobtracker, logging to /mnt/ephemeral-hdfs/logs/hadoop-root-jobtracker-ip-10-30-145-36.ec2.internal.out
Warning: $HADOOP_HOME is deprecated.

ec2-50-16-22-140.compute-1.amazonaws.com: starting tasktracker, logging to /mnt/ephemeral-hdfs/logs/hadoop-root-tasktracker-ip-10-159-2-31.ec2.internal.out
ec2-23-23-65-191.compute-1.amazonaws.com: starting tasktracker, logging to /mnt/ephemeral-hdfs/logs/hadoop-root-tasktracker-ip-10-158-45-69.ec2.internal.out
ec2-174-129-81-192.compute-1.amazonaws.com: starting tasktracker, logging to /mnt/ephemeral-hdfs/logs/hadoop-root-tasktracker-ip-10-29-137-62.ec2.internal.out
ec2-50-16-22-140.compute-1.amazonaws.com: Warning: $HADOOP_HOME is deprecated.
ec2-50-16-22-140.compute-1.amazonaws.com: 
ec2-23-23-65-191.compute-1.amazonaws.com: Warning: $HADOOP_HOME is deprecated.
ec2-23-23-65-191.compute-1.amazonaws.com: 
ec2-174-129-81-192.compute-1.amazonaws.com: Warning: $HADOOP_HOME is deprecated.
ec2-174-129-81-192.compute-1.amazonaws.com: 
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
13/02/24 04:11:32 INFO tools.DistCp: srcPaths=[s3n://ampcamp-data/wikistats_20090505-05]
13/02/24 04:11:32 INFO tools.DistCp: destPath=hdfs://ip-10-30-145-36.ec2.internal:9000/wiki/pagecounts
13/02/24 04:11:33 INFO tools.DistCp: sourcePathsCount=76
13/02/24 04:11:33 INFO tools.DistCp: filesToCopyCount=75
13/02/24 04:11:33 INFO tools.DistCp: bytesToCopyCount=18.5g
13/02/24 04:11:33 INFO mapred.JobClient: Running job: job_201302240411_0001
13/02/24 04:11:34 INFO mapred.JobClient:  map 0% reduce 0%
13/02/24 04:11:48 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000000_0, Status : FAILED
java.lang.NullPointerException
    at org.apache.hadoop.fs.s3native.NativeS3FileSystem$NativeS3FsInputStream.close(NativeS3FileSystem.java:106)
    at java.io.BufferedInputStream.close(BufferedInputStream.java:468)
    at java.io.FilterInputStream.close(FilterInputStream.java:172)
    at org.apache.hadoop.tools.DistCp.checkAndClose(DistCp.java:1386)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.copy(DistCp.java:434)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.map(DistCp.java:547)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.map(DistCp.java:314)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:00 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000000_1, Status : FAILED
java.lang.NullPointerException
    at org.apache.hadoop.fs.s3native.NativeS3FileSystem$NativeS3FsInputStream.close(NativeS3FileSystem.java:106)
    at java.io.BufferedInputStream.close(BufferedInputStream.java:468)
    at java.io.FilterInputStream.close(FilterInputStream.java:172)
    at org.apache.hadoop.tools.DistCp.checkAndClose(DistCp.java:1386)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.copy(DistCp.java:434)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.map(DistCp.java:547)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.map(DistCp.java:314)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:02 INFO mapred.JobClient:  map 3% reduce 0%
13/02/24 04:12:04 INFO mapred.JobClient:  map 7% reduce 0%
13/02/24 04:12:06 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000009_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 1
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:06 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000008_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 1
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:09 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000011_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 1
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:09 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000007_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 1
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:10 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000010_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 1
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:12 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000003_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 2
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:13 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000001_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 2
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:13 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000002_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 2
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:14 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000000_2, Status : FAILED
java.lang.NullPointerException
    at org.apache.hadoop.fs.s3native.NativeS3FileSystem$NativeS3FsInputStream.close(NativeS3FileSystem.java:106)
    at java.io.BufferedInputStream.close(BufferedInputStream.java:468)
    at java.io.FilterInputStream.close(FilterInputStream.java:172)
    at org.apache.hadoop.tools.DistCp.checkAndClose(DistCp.java:1386)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.copy(DistCp.java:434)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.map(DistCp.java:547)
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.map(DistCp.java:314)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:50)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:16 INFO mapred.JobClient:  map 0% reduce 0%
13/02/24 04:12:16 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000006_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 2
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:17 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000004_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 2
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:17 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000012_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 1
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:18 INFO mapred.JobClient: Task Id : attempt_201302240411_0001_m_000005_0, Status : FAILED
java.io.IOException: Copied: 0 Skipped: 0 Failed: 2
    at org.apache.hadoop.tools.DistCp$CopyFilesMapper.close(DistCp.java:582)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:436)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1059)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

13/02/24 04:12:27 INFO mapred.JobClient: Job complete: job_201302240411_0001
13/02/24 04:12:27 INFO mapred.JobClient: Counters: 6
13/02/24 04:12:27 INFO mapred.JobClient:   Job Counters 
13/02/24 04:12:27 INFO mapred.JobClient:     SLOTS_MILLIS_MAPS=401809
13/02/24 04:12:27 INFO mapred.JobClient:     Total time spent by all reduces waiting after reserving slots (ms)=0
13/02/24 04:12:27 INFO mapred.JobClient:     Total time spent by all maps waiting after reserving slots (ms)=0
13/02/24 04:12:27 INFO mapred.JobClient:     Launched map tasks=27
13/02/24 04:12:27 INFO mapred.JobClient:     SLOTS_MILLIS_REDUCES=0
13/02/24 04:12:27 INFO mapred.JobClient:     Failed map tasks=1
13/02/24 04:12:27 INFO mapred.JobClient: Job Failed: # of failed Map Tasks exceeded allowed limit. FailedCount: 1. LastFailedTask: task_201302240411_0001_m_000000
With failures, global counters are inaccurate; consider running with -i
Copy failed: java.io.IOException: Job failed!
    at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:1257)
    at org.apache.hadoop.tools.DistCp.copy(DistCp.java:667)
    at org.apache.hadoop.tools.DistCp.run(DistCp.java:881)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
    at org.apache.hadoop.tools.DistCp.main(DistCp.java:908)

Connection to ec2-23-20-148-178.compute-1.amazonaws.com closed.
Traceback (most recent call last):
  File "./spark_ec2.py", line 867, in <module>
    main()
  File "./spark_ec2.py", line 722, in main
    copy_ampcamp_data(master_nodes, opts)
  File "./spark_ec2.py", line 493, in copy_ampcamp_data
    "hdfs://`hostname`:9000/wiki/pagecounts")
  File "./spark_ec2.py", line 663, in ssh
    (opts.identity_file, opts.user, host, command), shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -t -o StrictHostKeyChecking=no -i /Users/andyk/.ec2/andyk-ec2.pem root@ec2-23-20-148-178.compute-1.amazonaws.com '/root/ephemeral-hdfs/bin/hadoop distcp s3n://ampcamp-data/wikistats_20090505-05 hdfs://`hostname`:9000/wiki/pagecounts'' returned non-zero exit status 25
```

**Comment by pwendell** [comment]
Are you using the launch script from shivarams repo or the one referred to
in the tutorial? You should be using the former... Its the most recent.
Shiv can point you to it

**Comment by andyk** [comment]
Oy. I'm using the ones at https://github.com/amplab/training-scripts

I don't see that Shivaram has forked either of them in his github account (https://github.com/shivaram?tab=repositories) so I assume when you say "Shivaram's repo" you might be talking about this one that I'm using.

**Comment by pwendell** [comment]
Ya that's the right one or at least the one I used. I thought maybe you
mixed up with the "ampcamp" one which I did

**Comment by shivaram** [comment]
Ugh. This seems to be a ugly Hadoop bug that has been discussed a couple of times on the Spark mailing list (https://groups.google.com/forum/#!searchin/spark-users/NativeS3FileSystem.java/spark-users/E30pyRhNmoM/PsNTv6d32YgJ). 
Its surprising that I've never run into this while launching ampcamp amis before.  I am wondering if this might have been correlated to some distcp's I ran earlier today. 

I cleared a bunch of empty files from the s3 -- Could you try again and let me know if you still run into this. You could also try a different bucket id by passing the flag --s3-stats-bucket

**Comment by andyk** [comment]
I was able to launch a cluster without a problem today, so closing this now.

**Comment by brjadams** [comment]
I just got this error.

cc-badams:training-scripts brian.adams$ ./spark-ec2 -i ../amplab-key.pem -k amplab-key --copy launch amplab-training
Setting up security groups...
Searching for existing cluster amplab-training...
Latest Spark AMI: ami-4c5fcd25
Launching instances...
Launched 5 slaves in us-east-1b, regid = r-d72800bf
Launched master in us-east-1b, regid = r-b49f61d8
Waiting for instances to start up...
Waiting 120 more seconds...
Copying SSH key ../amplab-key.pem to master...
ssh: connect to host ec2-54-224-225-186.compute-1.amazonaws.com port 22: Connection refused
Traceback (most recent call last):
  File "./spark_ec2.py", line 878, in <module>
    main()
  File "./spark_ec2.py", line 726, in main
    setup_cluster(conn, master_nodes, slave_nodes, zoo_nodes, opts, True)
  File "./spark_ec2.py", line 397, in setup_cluster
    ssh(master, opts, 'mkdir -p ~/.ssh')
  File "./spark_ec2.py", line 674, in ssh
    (opts.identity_file, opts.user, host, command), shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -t -o StrictHostKeyChecking=no -i ../amplab-key.pem root@ec2-54-224-225-186.compute-1.amazonaws.com 'mkdir -p ~/.ssh'' returned non-zero exit status 255

**Comment by pwendell** [comment]
Try running it again with --resume option.

Sometimes the nodes take longer than 120 seconds to start up.

**Comment by brjadams** [comment]
And by that you mean, 
./spark-ec2 -i ../amplab-key.pem -k amplab-key --resume amplab-training
?

**Comment by pwendell** [comment]
Yes try:

./spark-ec2 -i ../amplab-key.pem -k amplab-key --copy launch
amplab-training --resume

if that doesn't work, then it might make sense to destroy and re-create the
cluster using a longer wait period.

./spark-ec2 destroy amplab-training
./spark-ec2 -i ../amplab-key.pem -k amplab-key --copy launch
amplab-training -w 500

The issue here is that there is that the script waits for a while until it
thinks the ec2 instances are spun up... if that wait period is too short
then you'll get a connection refused.

**Comment by brjadams** [comment]
Well that's frustrating

**Comment by JoshRosen** [comment]
@pwendell There was a recent Spark pull request to add automatic retry to `spark-ec2` when sshing into a cluster: https://github.com/mesos/spark/pull/555

Can we port this technique to the ampcamp scripts?

**Comment by brjadams** [comment]
BTW - What is a rough estimate for the cost of running through the amp-camp exercises? This is something I think many would like to know.

**Comment by JoshRosen** [comment]
@brjadams The default [cluster launch instructions](http://ampcamp.berkeley.edu/big-data-mini-course/launching-a-spark-shark-cluster-on-ec2.html) from the AMP Camp tutorial launch a cluster containing 6 `m1.xlarge` Amazon EC2 nodes.  According to [ec2instances.info](http://www.ec2instances.info/), these nodes cost $0.48 / hour to run, so you're looking at $2.88 / hour to run the whole cluster (remember to shut it down when you're finished so you don't continue to get billed!).

Amazon charges for EC2 instances in terms of whole instance hours, so you'll have to pay a minimum of $2.88 every time you launch a default AMP Camp cluster through the EC2 script, regardless of how long you use it.  For this reason, I prefer to use the `--resume` command to fix clusters that don't start properly instead of destroying them and launching new ones.

You might be able to save money by using [spot instances](http://aws.amazon.com/ec2/spot-instances) for the worker machines, dropping the cost to $0.48 / hour to run the master node plus as low as $0.052 / hour for each worker (the exact pricing depends on the current spot bid prices).  The downside to this approach is that spot instances can be terminated if the bid price rises, so you're trading off between cost and having to restart your worker machines, configure the cluster to use those new machines, and re-load your data.  Spark's EC2 launch scripts have support for spot instances, but the AMP Camp tutorial doesn't describe it.

**Comment by brjadams** [comment]
@JoshRosen Thank you very much for the breakdown!
