### ISSUE TITLE
Make logging output less verbose in exercises

### ISSUE THREAD

**Issue by andyk** [amplab/training#41]
@pwendell noticed that when you run KMeans there is a bunch of output that makes it hard to see the stuff they are asked to print.

We should either:
1) Change the log level to WARN (though this has some draw backs)
2) Remove sc.stop() at the end, so at least the expected output is printed out when the user sees it.
3) Have them pipe stderr to a file.

**Comment by andyk** [comment]
Also, just noticed that when I add the lines to do the count, though it seems to be completing the query as expected and giving me the correct answer, it shows the output from an exception which might confuse users.

At very least if these exceptions are normal, we should explain this in the tutorial text.

``` text
...
13/02/25 13:56:44 INFO spark.SparkContext: Job finished: count at WikipediaKMeans.scala:31, took 12.214210058 s
Number of records 802450
13/02/25 13:56:44 INFO spark.MapOutputTrackerActor: MapOutputTrackerActor stopped!
13/02/25 13:56:44 INFO network.ConnectionManager: Selector thread was interrupted!
13/02/25 13:56:44 INFO network.ConnectionManager: ConnectionManager stopped
13/02/25 13:56:44 INFO storage.MemoryStore: MemoryStore cleared
13/02/25 13:56:44 INFO storage.BlockManager: BlockManager stopped
13/02/25 13:56:44 INFO storage.BlockManagerMasterActor: Stopping BlockManagerMaster
13/02/25 13:56:44 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
13/02/25 13:56:44 INFO spray.HttpService: Stopped
13/02/25 13:56:44 INFO spray.SprayCanRootService: spray RootService stopped
[INFO] [02/25/2013 13:56:45.9] [spray-io-worker-0] [IoWorker] IoWorker thread 'spray-io-worker-0' stopped
[INFO] [02/25/2013 13:56:45.15] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteClientShutdown@akka://spark@ip-10-141-132-24.ec2.internal:6068613/02/25 13:56:45 INFO spark.SparkContext: Successfully stopped SparkContext

[INFO] [02/25/2013 13:56:45.16] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteClientShutdown@akka://spark@ip-10-143-135-38.ec2.internal:54986
[INFO] [02/25/2013 13:56:45.17] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkMaster@ec2-50-17-76-215.compute-1.amazonaws.com:7077
[INFO] [02/25/2013 13:56:45.39] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteClientShutdown@akka://spark@ip-10-143-137-85.ec2.internal:60869
[INFO] [02/25/2013 13:56:45.40] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkExecutor@ip-10-143-135-38.ec2.internal:49350
[INFO] [02/25/2013 13:56:45.40] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkExecutor@ip-10-141-132-24.ec2.internal:44288
[INFO] [02/25/2013 13:56:45.40] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkExecutor@ip-10-143-137-85.ec2.internal:32898
[ERROR] [02/25/2013 13:56:45.49] [spark-8] [ActorSystem(spark)] RemoteServerError@akka://spark@10.141.132.78:46840] Error[java.nio.channels.ClosedChannelException:null
        at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:144)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:342)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:242)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:489)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:444)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:366)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processWriteTaskQueue(AbstractNioWorker.java:362)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
]
[INFO] [02/25/2013 13:56:45.87] [spark-akka.actor.default-dispatcher-1] [ActorSystem(spark)] RemoteServerShutdown@akka://spark@10.141.132.78:46840
```

I ran it again and even more exceptions get printed, again in spite of the answer coming back correctly:

``` text
...
13/02/25 14:03:55 INFO scheduler.DAGScheduler: Completed ResultTask(0, 15)
13/02/25 14:03:55 INFO scheduler.DAGScheduler: Stage 0 (map at WikipediaKMeans.scala:27) finished in 11.831 s
13/02/25 14:03:55 INFO spark.SparkContext: Job finished: count at WikipediaKMeans.scala:31, took 11.881358891 s
Number of records 802450
13/02/25 14:03:55 INFO spark.MapOutputTrackerActor: MapOutputTrackerActor stopped!
13/02/25 14:03:55 INFO network.ConnectionManager: Selector thread was interrupted!
13/02/25 14:03:55 INFO network.ConnectionManager: ConnectionManager stopped
13/02/25 14:03:55 INFO storage.MemoryStore: MemoryStore cleared
13/02/25 14:03:55 INFO storage.BlockManager: BlockManager stopped
13/02/25 14:03:55 INFO storage.BlockManagerMasterActor: Stopping BlockManagerMaster
13/02/25 14:03:55 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
13/02/25 14:03:55 INFO spray.HttpService: Stopped
13/02/25 14:03:55 INFO spray.SprayCanRootService: spray RootService stopped
[INFO] [02/25/2013 14:03:55.691] [spray-io-worker-0] [IoWorker] IoWorker thread 'spray-io-worker-0' stopped
13/02/25 14:03:55 INFO spark.SparkContext: Successfully stopped SparkContext
[INFO] [02/25/2013 14:03:55.697] [spark-akka.actor.default-dispatcher-4] [ActorSystem(spark)] RemoteClientShutdown@akka://spark@ip-10-143-135-38.ec2.internal:55017
[INFO] [02/25/2013 14:03:55.697] [spark-akka.actor.default-dispatcher-4] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkExecutor@ip-10-143-135-38.ec2.internal:52056
[INFO] [02/25/2013 14:03:55.698] [spark-akka.actor.default-dispatcher-4] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkMaster@ec2-50-17-76-215.compute-1.amazonaws.com:7077
[INFO] [02/25/2013 14:03:55.714] [spark-akka.actor.default-dispatcher-4] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkExecutor@ip-10-143-137-85.ec2.internal:48075
[INFO] [02/25/2013 14:03:55.715] [spark-akka.actor.default-dispatcher-4] [ActorSystem(spark)] RemoteClientShutdown@akka://spark@ip-10-143-137-85.ec2.internal:40885
[INFO] [02/25/2013 14:03:55.715] [spark-akka.actor.default-dispatcher-4] [ActorSystem(spark)] RemoteClientShutdown@akka://spark@ip-10-141-132-24.ec2.internal:58859
[INFO] [02/25/2013 14:03:55.719] [spark-akka.actor.default-dispatcher-4] [ActorSystem(spark)] RemoteClientShutdown@akka://sparkExecutor@ip-10-141-132-24.ec2.internal:43705
[ERROR] [02/25/2013 14:03:55.737] [spark-7] [ActorSystem(spark)] RemoteServerError@akka://spark@10.141.132.78:40612] Error[java.nio.channels.ClosedChannelException:null
        at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:144)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:342)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:242)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:489)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:444)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:366)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processWriteTaskQueue(AbstractNioWorker.java:362)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
]
[ERROR] [02/25/2013 14:03:55.738] [spark-8] [ActorSystem(spark)] RemoteServerError@akka://spark@10.141.132.78:40612] Error[java.nio.channels.ClosedChannelException:null
        at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:144)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:342)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:242)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:489)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:444)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:366)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processWriteTaskQueue(AbstractNioWorker.java:362)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
]
[ERROR] [02/25/2013 14:03:55.740] [spark-3] [ActorSystem(spark)] RemoteServerError@akka://spark@10.141.132.78:40612] Error[java.nio.channels.ClosedChannelException:null
        at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:144)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:342)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:242)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:489)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:444)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:366)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processWriteTaskQueue(AbstractNioWorker.java:362)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
]
[ERROR] [02/25/2013 14:03:55.741] [spark-6] [ActorSystem(spark)] RemoteServerError@akka://spark@10.141.132.78:40612] Error[java.nio.channels.ClosedChannelException:null
        at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:144)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:342)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:242)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:489)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:444)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:366)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processWriteTaskQueue(AbstractNioWorker.java:362)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
]
[ERROR] [02/25/2013 14:03:55.744] [spark-6] [ActorSystem(spark)] RemoteServerError@akka://spark@10.141.132.78:40612] Error[java.nio.channels.ClosedChannelException:null
        at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:144)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:342)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:242)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:489)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:444)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:366)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processWriteTaskQueue(AbstractNioWorker.java:362)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
]
[ERROR] [02/25/2013 14:03:55.764] [spark-7] [ActorSystem(spark)] RemoteServerError@akka://spark@10.141.132.78:40612] Error[java.nio.channels.ClosedChannelException:null
        at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:144)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:342)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$PooledSendBuffer.transferTo(SocketSendBufferPool.java:242)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:489)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:444)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:366)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processWriteTaskQueue(AbstractNioWorker.java:362)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
]
```

**Comment by shivaram** [comment]
Couple of suggestions:
1. For scala and java we can add the following line at the beginning of main to make the output less verbose
   Logger.getLogger("spark").setLevel(Level.WARN)

I think the streaming exercises do the same thing ?
1. Can you check if you get the errors at the end if you remove sc.stop() from the program ? I am not sure why those exceptions get printed, but I think they are triggered from sc.stop

**Comment by shivaram** [comment]
Also I am not sure how to make the python output less verbose. I think we will need to mess with log4j.properties to do that.

**Comment by shivaram** [comment]
I tried to fix this for python in https://github.com/amplab/training/commit/11e8978639737d9800c9d624d8fe3d4e20d01fda . Didn't test this on the AMI though

**Comment by andyk** [comment]
Ok, I didn't try it in python yet.

**Comment by andyk** [comment]
Removing the call to sc.stop does cause the exceptions to stop happening!

**Comment by shivaram** [comment]
Removed from templates and text in https://github.com/amplab/training/commit/9691754c7f7ce89e06b2b9fb45725f6683f53c97

**Comment by JoshRosen** [comment]
Another option in Python is to to configure the logging through Py4J:

``` python
from py4j.java_gateway import java_import
java_import(sc._jvm, "org.apache.log4j.Logger")
java_import(sc._jvm, "org.apache.log4j.Level")
sc._jvm.Logger.getLogger("spark").setLevel(sc._jvm.Level.WARN)
```

Unfortunately, this has to take place after the SparkContext is created (since SparkContext manages the Py4J instance), so a bit of logging would still be printed while SparkContext is starting up:

**Comment by shivaram** [comment]
I was wondering how to get a handle of the jvm. Thanks for the tip. This is a bit more verbose, so I guess we can stick to the classpath trick for now.

**Comment by pwendell** [comment]
So removing stop() actually doesn't work for the Java and Scala examples. The issue is that sbt overrides System.exit(), so the JVM will actually just hang if stop() isn't called. I have made a separate pull request to Spark which should remove these akka log messages:

https://github.com/mesos/spark/pull/498

**Comment by shivaram** [comment]
Thanks for tracking this down. So we should add sc.stop() back into the code and text ?

**Comment by pwendell** [comment]
I took care of this already in 5f3cf9.

I think this issue is now solved (I can't reproduce it anymore). But since it was not deterministic in the first place, I want to run through it again later to be sure.

**Comment by shivaram** [comment]
Oh cool. I can also test this later today to double check.

**Comment by shivaram** [comment]
Tested this in all 3 languages.
